services:
  - type: web
    name: web-gis-scraper-backend
    env: docker
    plan: free
    autoDeploy: true
    branch: feature/docker-deploy # שנה לפי הצורך
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - "**/*.py"
        - "requirements.txt"
        - "Dockerfile"
        - "render.yaml"
    envVars:
      - key: PORT
        value: 8000
